Repository CubeCoders/AMPTemplates, pull requests merged in 2022-09, with the labels that each got.

#165 Add Post Scriptum
  post-scriptum-serverconfig.json
  post-scriptum-servermetaconfig.json
  post-scriptum.kvp
Labels: enhancement, good first issue, Windows, Linux

#38 Add TeamSpeak 3 Config
  teamspeak3.kvp
  teamspeak3config.json
  teamspeak3metaconfig.json
  teamspeak3server.ini
Labels: Windows, Linux, AwaitingFeatures

#152 Add Vintage Story
  vintage-story.kvp
  vintage-storyconfig.json
  vintage-storymetaconfig.json
Labels: Windows, Linux

#188 Add Conan Exiles Docker Support
  conan-exiles.kvp
Labels: enhancement, Windows, Linux, NeedsTesting, Wine

#156 Stationeers: Various updates for new dedicated server build
  stationeers-legacy.kvp
  stationeers-legacyconfig.json
  stationeers-legacymetaconfig.json
  stationeers.kvp
  stationeersconfig.json
  stationeersmetaconfig.json
Labels: enhancement, Windows, Linux

#162 Geyser: overhaul of template
  geyser.kvp
  geyserconfig.json
  geyserupdates.json
Labels: Windows, Linux, AwaitingFeatures

#134 Initial Starbound Generic Config
  starbound.kvp
  starbound_server.config
  starboundconfig.json
  starboundmetaconfig.json
Labels: Windows, Linux

#191 Add Blackwake
  blackwake.kvp
  blackwakeconfig.json
  blackwakemetaconfig.json
Labels: Windows, Linux, Wine

#201 Update Valheim and ValheimPlus
  valheim.kvp
  valheimconfig.json
  valheimplus.kvp
Labels: enhancement, Windows, Linux

#202 Update 7D2D Network Option
  seven-days-to-dieconfig.json
Labels: enhancement, Windows, Linux

#197 Add Assetto Corsa Competizione
  assetto-corsa-comp.kvp
  assetto-corsa-compconfig.json
  assetto-corsa-compmetaconfig.json
Labels: Windows, Linux, Wine

#185 Just Cause 3 Multiplayer Game Support Draft
  jc3mp.kvp
  jc3mpconfig.json
  jc3mpmetaconfig.json
  jc3mpserverconfig.json
Labels: enhancement, Windows, Linux
