Repository CubeCoders/AMPTemplates, pull requests merged in 2022-08, with the labels that each got.

#163 Add GatekeeperV2 Bot
  gatekeeperv2.kvp
  gatekeeperv2config.json
  gatekeeperv2metaconfig.json
Labels: Linux, AwaitingFeatures

#174 Update Empyrion Config Manifest
  empyrion-galactic-survivalconfig.json
Labels: enhancement

#166 Add Longvinter
  longvinter.kvp
  longvinterconfig.json
  longvintergame.ini
  longvintermetaconfig.json
Labels: Windows, Linux

#168 Add Veloren
  veloren.kvp
  velorenconfig.json
  velorenmetaconfig.json
  velorensettings.ron
Labels: bug, Windows, Linux

#180 Necesse Game Support Draft
  necesse.kvp
  necesseconfig.json
  necessemetaconfig.json
  necesseserverconfig.cfg
Labels: Windows, Linux

#182 Update 7d2d Config
  seven-days-settings184.xml
  seven-days-settings196.xml
  seven-days-settings200-203.xml
  seven-days-settings204.xml
  seven-days-to-die.kvp
  seven-days-to-dieconfig.json
  seven-days-to-diemetaconfig.json
  seven-days-to-dieupdates.json
Labels: enhancement, Windows, Linux
