Repository CubeCoders/AMPTemplates, pull requests merged in 2022-12, with the labels that each got.

#250 Update Empyrion - Custom Scenario and Default Backup Exclusions
  empyrion-galactic-survivalconfig.json
  empyrion-galactic-survivalupdates.json
  exclusions/.backupExclusionsEmpyrion1
Labels: enhancement, Windows

#251 Update Empyrion - Backup Exclude Toggle
  empyrion-galactic-survivalconfig.json
  empyrion-galactic-survivalupdates.json
Labels: enhancement, Windows

#252 Update 7D2D - Default Backup Exclude
  exclusions/.backupExclusions7d2d1
  seven-days-to-dieconfig.json
  seven-days-to-dieupdates.json
Labels: enhancement, Windows, Linux

#241 Merged Valheim and Valheim Plus templates.
  valheim.kvp
  valheimconfig.json
  valheimmetaconfig.json
  valheimplus.kvp
  valheimupdates.json
Labels: enhancement, Windows, Linux

#264 Update GatekeeperV2
  gatekeeperv2.kvp
Labels: enhancement, Linux
