Repository CubeCoders/AMPTemplates, pull requests merged in 2022-11, with the labels that each got.

#224 Added Seven Days to Die Undead Legacy Template
  seven-days-settings-undead-legacy-experimental.xml
  seven-days-settings-undead-legacy-stable.xml
  seven-days-to-die.kvp
  seven-days-to-dieconfig.json
  seven-days-to-diemetaconfig.json
  seven-days-to-dieupdates.json
Labels: enhancement, good first issue, Windows, Linux

#193 Add Call of Duty: Modern Warfare 3
  call-of-dutymw3.kvp
  call-of-dutymw3config.json
  call-of-dutymw3metaconfig.json
Labels: Windows, Linux, Wine

#217 Add Unreal Tournament (UT99)
  ut99.kvp
  ut99UnrealTournament.ini
  ut99config.json
  ut99metaconfig.json
Labels: Windows, Linux

#218 Add Unreal Tournament 2004
  ut2004.kvp
  ut2004config.json
  ut2004metaconfig.json
Labels: Windows, Linux

#115 Add Portal Knights
  portal-knights.kvp
  portal-knightsconfig.json
  portal-knightsmetaconfig.json
  portal-knightsserver_config.json
Labels: Windows, Linux, Wine

#234 Update Satisfactory Release Stream
  satisfactoryconfig.json
Labels: bug, enhancement, Windows, Linux

#240 Update TeamSpeak 3 License Path
  teamspeak3config.json
  teamspeak3server.ini
Labels: bug, Windows, Linux
