Repository CubeCoders/AMPTemplates, pull requests merged in 2022-06, with the labels that each got.

#131 Update v-risingconfig.json
  v-risingconfig.json
Labels: enhancement

#129 Core Keeper Generic Template
  core-keeper.kvp
  core-keeperconfig.json
  core-keepermetaconfig.json
  core-keeperserverconfig.json
Labels: Windows, Linux

#43 Add Wreckfest
  wreckfest.kvp
  wreckfestconfig.json
  wreckfestmetaconfig.json
Labels: Windows, Linux, NeedsTesting, Wine

#136 Add Carrier Command 2
  carrier-command2.kvp
  carrier-command2config.json
  carrier-command2metaconfig.json
  carrier-command2server_config.xml
Labels: Windows, Linux, NeedsTesting, Wine

#146 Add Assetto Corsa Competizione
  assetto-corsa-comp.kvp
  assetto-corsa-compconfig.json
  assetto-corsa-compmetaconfig.json
Labels: Windows, Linux, Wine

#143 Add Assetto Corsa
  assetto-corsa.kvp
  assetto-corsaconfig.json
  assetto-corsametaconfig.json
Labels: Windows, Linux, NeedsTesting, Wine

#155 Add Empyrion Galactic Survival
  empyrion-galactic-survival.kvp
  empyrion-galactic-survivalconfig.json
  empyrion-galactic-survivalmetaconfig.json
  empyrion-galactic-survivalports.json
  empyrion-galactic-survivalupdates.json
  empyriondedicated.yaml
Labels: Windows, Linux, NeedsTesting, Wine
