Repository CubeCoders/AMPTemplates, pull requests merged in 2022-05, with the labels that each got.

#125 Initial Commit - V-Rising
  v-rising.kvp
  v-risingconfig.json
  v-risingmetaconfig.json
Labels: good first issue, Windows

#114 Add Hurtworld
  hurtworld.kvp
  hurtworldconfig.json
  hurtworldmetaconfig.json
Labels: Windows, Linux

#95 Add The Isle (EVRIMA)
  theisle-evrima.kvp
  theisle-evrimaconfig.json
  theisle-evrimagame.ini
  theisle-evrimametaconfig.json
Labels: Windows, Linux, NeedsTesting

#133 Update Risk of Rain 2
  risk-of-rain-2.kvp
  risk-of-rain-2config.json
  risk-of-rain-2metaconfig.json
Labels: enhancement, Windows, Linux, NeedsTesting

#96 Add Xonotic Dedicated Server
  xonotic.kvp
  xonoticconfig.json
  xonoticmetaconfig.json
  xonoticserver.cfg
Labels: Windows, Linux
