Repository CubeCoders/AMPTemplates, pull requests merged in 2022-02, with the labels that each got.

#68 Astroneer: Various updates
  astroneer.kvp
  astroneerconfig.json
  astroneermetaconfig.json
Labels: Windows

#50 Add Unturned template
  unturned.kvp
  unturnedconfig.json
  unturnedconfigfile.dat
  unturnedmetaconfig.json
  unturnedworkshopconfig.json
Labels: Windows, Linux

#67 Convert Insurgency Sandstorm to base config
  insurgencysandstorm.kvp
  insurgencysandstormconfig.json
  insurgencysandstormmetaconfig.json
Labels: enhancement, Windows, Linux

#70 Risk of Rain Steam SDK Fix
  risk-of-rain-2.kvp
Labels: bug

#76 Unturned: Add sleep settings
  unturned.kvp
Labels: enhancement, Windows, Linux

#75 Create Stationeers Config
  stationeers.kvp
  stationeersconfig.json
  stationeersmetaconfig.json
Labels: enhancement, Windows, Linux, AwaitingFeatures

#81 Update Space Engineers
  space-engineers-generic.kvp
  space-engineers-genericconfig.json
Labels: bug, enhancement, Windows

#80 Unturned: update telnet login format
  unturned.kvp
Labels: enhancement, Linux

#41 Add Pavlov VR template
  pavlov-vr.kvp
  pavlov-vrconfig.json
  pavlov-vrconfigfile.ini
  pavlov-vrmetaconfig.json
Labels: Linux

#82 Update Stationeers
  stationeers.kvp
  stationeersconfig.json
Labels: enhancement, Windows, Linux

#84 Fix Insurgency Sandstorm
  insurgencysandstorm.kvp
Labels: bug, Windows, Linux
