Repository CubeCoders/AMPTemplates, pull requests merged in 2022-03, with the labels that each got.

#69 Re-Write of Squad [Draft]
  squad-dedicated-server.kvp
  squad-dedicated-serverconfig.json
  squad-dedicated-servermetaconfig.json
Labels: Windows, Linux, AwaitingFeatures

#47 Add Wurm Unlimited
  wurm-unlimited.kvp
  wurm-unlimitedconfig.json
  wurm-unlimitedmetaconfig.json
Labels: Windows, Linux

#79 Add Killing Floor 2
  killing-floor-2.kvp
  killing-floor-2config.json
  killing-floor-2metaconfig.json
Labels: enhancement, Windows, Linux, AwaitingFeatures

#91 Add Terraria module
  terraria.kvp
  terrariaconfig.json
  terrariametaconfig.json
  terrariaserverconfig.txt
Labels: enhancement, Windows, Linux

#90 Add tModLoader module
  tmodloader.kvp
  tmodloaderconfig.json
  tmodloadermetaconfig.json
  tmodloaderserverconfig.txt
Labels: enhancement, Windows, Linux

#86 Add Eco template
  eco.kvp
  ecoconfig.json
  ecometaconfig.json
Labels: Windows, Linux, NeedsTesting

#100 Update Space Engineers
  space-engineers-generic.kvp
  space-engineers-genericconfig.json
  space-engineers-genericmetaconfig.json
Labels: bug, Windows

#93 Add Mordhau Config
  mordhau-config.json
  mordhau-metaconfig.json
  mordhau.kvp
Labels: enhancement, Windows, Linux, NeedsTesting

#92 Add The Isle (Legacy)
  theisle-legacy.kvp
  theisle-legacyconfig.json
  theisle-legacygame.ini
  theisle-legacymetaconfig.json
Labels: bug, Windows, Linux, Proton, NeedsTesting
