Repository CubeCoders/AMPTemplates, pull requests merged in 2023-03, with the labels that each got.

#27 Add DayZ
  dayz-experimental.kvp
  dayz-experimentalconfig.json
  dayz-experimentalmetaconfig.json
  dayz-experimentalmodscript.sh
  dayz-experimentalserver.cfg
  dayz-experimentalupdates.json
  dayz-original.kvp
  dayz-originalconfig.json
  dayz-originalmetaconfig.json
  dayz-originalserver.cfg
  dayz-originalupdates.json
Labels: enhancement, Windows, Linux

#203 Add Arma 3 (generic)
  arma3.kvp
  arma3basic.cfg
  arma3config.json
  arma3metaconfig.json
  arma3modscript.sh
  arma3server.cfg
  arma3updates.json
Labels: Windows, Linux

#121 Add Arma Reforger
  arma-reforger.kvp
  arma-reforgerconfig.json
  arma-reforgermetaconfig.json
  arma-reforgerserver.json
  arma-reforgerupdates.json
Labels: Windows, Linux

#300 Conan Exiles - Add Workshop Mod Support
  conan-exiles.kvp
  conan-exilesconfig.json
Labels: enhancement, Windows, Linux, Wine

#192 Add Path of Titans
  path-of-titans.kvp
  path-of-titansconfig.json
  path-of-titansmetaconfig.json
  path-of-titansupdates.json
Labels: bug, Windows, Linux, AwaitingFeatures
